2.17 Разметка главной страницы
htmlacademy-htmlcss/178043-technomart-29 pull request #2
Opened 2020-09-21 21:07 UTC by Lyukman

2020-09-22 02:36 UTC, ego-o requested changes
Разметка получилась достаточно хорошей. Соблюдено и форматирование кода, и заголовки следуют все по своим уровням вложенности, молодец! 

Из комментариев, большая чать пожалуй филосовская, на подумать "а как правильней" или "как лучше", однако, есть и ошибки. Те комментарии, которые помечены как `рекомендация` ошибкой не считаются.

2020-09-22 02:36 UTC, ego-o commented on index.html
> +        <a href="blank.html">ОТКРЫТЬ КАТАЛОГ</a>
`Рекомендация`

Не обязательно в разметке писать буквы в верхнем регистре. Сделать их большими можно будет при помощи CSS. Выбор между капсом и простым начертанием в разметке стоит делать в пользу того, как старница будет смотреться без стилей. В данном случае, кнопки у слайдеров и ссылка открыть каталог могут смотреться не очеь консистентно, ибо написаны в разных стилях. 

![image](https://user-images.githubusercontent.com/13464048/93838024-b4b64600-fca1-11ea-9f30-b96a76417422.png)

2020-09-22 02:36 UTC, ego-o commented on index.html
> +          <a href="#"><img src="file/DeWALT.png" width="146" height="44" alt="Логотип DeWALT"></a>
Имена всех подключаемых файлов должны быть написаны в нижнем регистре и должны содержать только латинские символы. [Критерий Б14](https://up.htmlacademy.ru/htmlcss/29/criteries#b14). 

Это важно, потому что в linux и windows разные подходы к файлам. Для windows по барабану, в каком регистре будут у файла символы, для нее `Image.png` и `IMAGE.PNG` будут два одинаковых файла. В Linux такой фокус уже не прокатит, для него регистр букв имеет значение, а сервера, на которых лежат файлы, в 90% случаев на Linux.
И получается, что мы легко можем попасть в такую ситуацию, когда файл у нас с именем `IMAGE.PNG`, а подключаем мы его на странице как `Image.png`. На Windows все будет работать, картинка загрузится, покажется, а когда код попадет на боевой сервер - работать перестанет. 

Или другая ситуация. Имеем сервер на Linux, в котором мы создаем два файла `button.js` и `Button.js` - два скрипта с какими то действиями для разных кнопок. Так как мы в линуксе, то там это у нас два разных файла. Мы сохраняем их на сервере в Git и идем на свой домашний компьютер под windows, чтобы их отредактировать. Но при попытке получить их из Git-a, мы получаем вместо двух файлов один и предупреждение в придачу, что один из файлов, при доставании их из Git был затерт. Потому что windows не видит между ними разницы. И теперь выкручивайся как хочешь :)

Поэтому, берем за правило - все имена файлов и папок всегда только в нижнем регистре, и только латинскими буквами.

И так как ты работаешь сокрей всего под windows, возникнет проблема при попытке переименовать там файлы изображений в нижний регистр и зафиксировать это. Для windows, что ты переименовал, что нет, файл остался тот же и имя то же, поэтому Git переименования тоже не заметит. Тут прийдется разбить на два коммита. В первом - удалить все изображения из папки img, во втором - вставить их обратно, но уже с именами в нужном регистре

2020-09-22 02:36 UTC, ego-o commented on index.html
> +        <li><a href="#">Кредит</a></li>
[Кнопка или ссылка?](https://www.notion.so/1aba970039f4468e98250c68f7dc07bb)

2020-09-22 02:36 UTC, ego-o commented on index.html
> +      <a href="#">Заблудились? НапиШИТЕ НАМ!</a>
Тут тоже что-то с регистром странное

2020-09-22 02:36 UTC, ego-o commented on index.html
> +        <label>Обратная связь:<a href="mailto:mail@htmlacademy.ru" >mail@htmlacademy.ru</a></label>
Тег `<label>` здесь не требуется, он нужен только для тегов `<input>`, чтобы задавать им текстовое орисание. У ссылки же текстовое описание содержится между открывающим и закрывающим тегом. Для чего требуется текстовое описание мы еще дойдем, в лекции про доступность.

2020-09-22 02:36 UTC, ego-o commented on index.html
> +    <!-- Здесь будет форма логина -->
На макете у нас нигде вроде-бы не представлена форма логина, поэтому в верстке она не нужна. Поправь, если ошибаюсь

2020-09-22 02:36 UTC, ego-o commented on index.html
> +    <!-- Здесь будет форма регистрации -->
На макете у нас, как и с логином, нигде вроде-бы не представлена форма регистрации, поэтому в верстке она не нужна. Поправь, если ошибаюсь

2020-09-22 02:36 UTC, ego-o commented on index.html
> +        равнодушными любителей сэкономить на гастарбайтерах.<br><br>
Делать абзацы через `<br><br>` - считается грубой ошибкой. Если нужно несколько абзацев - нужно разбить их на несколько тегов `<p>`. [Критерий Б4](https://up.htmlacademy.ru/htmlcss/29/criteries#b14)

2020-09-22 07:53 UTC, Lyukman commented on index.html
> +      <h2>Панель</h2>
Согласен, панель не самое подходящее название, не знал как назвать. "Популярные разделы каталога" я думаю тоже не самое информативное название. Эти кнопки по сути являются фильтрами всего каталога интернет-магазина.

2020-09-22 07:58 UTC, Lyukman commented on index.html
> +      <a href="#">Заблудились? НапиШИТЕ НАМ!</a>
Не понял по поводу регистра? Значения скопированы в точности с макета. Они же потом будут приводиться к стилями к точному соответствию макетного представления. Или ты про что-то другое?

2020-09-22 08:01 UTC, Lyukman commented on index.html
> +    <!-- Здесь будет форма логина -->
Да, в макете нет, хотел по аналогии с барбершопом попробовать попАп формы сделать.

2020-09-22 08:04 UTC, Lyukman commented on index.html
> +        равнодушными любителей сэкономить на гастарбайтерах.<br><br>
Я понимал это как значение наполняемое контент менеджером. Поэтому вставил контент в один параграф. Но так же согласен что рядом есть <ul> который должен тоже из админки заполняться.

2020-09-22 08:05 UTC, ego-o commented on index.html
> +      <h2>Панель</h2>
Нет, это не совсем фильтры. Фильтруются обычно товары, по каким-либо свойствам, которые принадлежат именно товарам (цена, цвет, раздел). Это же разделы каталога, папочки, по которым раскидан товар, и отсюда по сути можно быстро перейти в интересующий раздел с товарами.

Это разделы каталогоа, в которых лежит товар
![image](https://user-images.githubusercontent.com/13464048/93857476-0aa3e180-fcd4-11ea-817d-a0f9284e75c6.png)

Это уже фильтры, по свойствам товаров
![image](https://user-images.githubusercontent.com/13464048/93857537-2ad3a080-fcd4-11ea-906e-0881cdfaef61.png)

Как лучше озаглавить эту секцию страницы, тут уже смотри сам)

2020-09-22 08:10 UTC, ego-o commented on index.html
> +      <a href="#">Заблудились? НапиШИТЕ НАМ!</a>
Я про то, как записан текст в ссылке - `НапиШИТЕ НАМ!`. Сейчас на странице нет никаких стилей, и смотрится такой текст на странице не очень. То, что ты скопировал его с макета, это хорошо, ускорил себе время, но на такие вещи стоит обращать внимание. Дизайнер, в творчиском порыве, мог писать и так и сяк, да и он тоже человек, может совершать ошибки. Поэтому, некоторые вещи иногда приходится нормализовывать.

Если в браузере пользователя по каким-то причинам не загрузился ни CSS, ни JavaScript, то он увидит только голую HTML разметку. Страница при этом должна даже без стилей выглядеть опрятно и быть читаемой, похожей на документ Microsoft Word. Не должно быть никаикх гигантских иконок и картинок, занимающих весь экран пользователя. Не должно быть хаотично разбросанного текста, где выравнивание то по левому краю, то по правому, то по центру, и где-то еще разбросаны непонятные отступы.

2020-09-22 08:12 UTC, ego-o commented on index.html
> +    <!-- Здесь будет форма логина -->
В техномарте тоже будет два попап окна, один с картой, другой с формой обратной связи

2020-09-22 08:13 UTC, Lyukman commented on index.html
> +      <h2>Популярные ПРОИзводители:</h2>
Такое значение из макета. Я понял, это специально сделано, с тем чтобы потом стилями поправить и не зависеть от регистра контента.

2020-09-22 08:13 UTC, Lyukman commented on index.html
> +        <a href="blank.html">ОТКРЫТЬ КАТАЛОГ</a>
Из макета

2020-09-22 08:13 UTC, ego-o commented on index.html
> +        равнодушными любителей сэкономить на гастарбайтерах.<br><br>
Редакторы текста внутри различных CMS вполне умеют вставлять параграфы, поэтому, это считается ошибкой

2020-09-22 08:17 UTC, ego-o commented on index.html
> +      <h2>Популярные ПРОИзводители:</h2>
А мне кажется, что это мини-ловушки от академии) В комментарии ниже я уже отписал, почему такого быть не должно. Ну и вот ссылку прикреплю на всякий случай, зря чтоль статью писал :) https://www.notion.so/JavaScript-4138e961a41249aba568fdd94c6e7b6d

2020-09-22 08:28 UTC, Lyukman commented on index.html
> +        <li><a href="#">Кредит</a></li>
Не понял в чем замечание? Это можно сделать как попАп и/или отдельной страницей в качестве фолбека.

2020-09-22 08:29 UTC, Lyukman commented on index.html
> +      <a href="#">Заблудились? НапиШИТЕ НАМ!</a>
Данные скопированы из макета. Пояснения выше.

2020-09-22 08:35 UTC, Lyukman commented on index.html
> +    <!-- Здесь будет форма логина -->
Ок, я их в макете не нашел.

2020-09-22 08:43 UTC, Lyukman commented on index.html
> +        </figure>
Я полагаю, что изображение контентное. Т.к. чтобы освежить сайт при новой поставке товаров, он будет заменяться. Согласен что для инструментов это не так часто происходит, как скажем для одежды или обуви, там линейка меняется с наступлением нового сезона. С другой стороны, наверное, там будет слайд про доставку или что-то подобное, которое будет иметь чисто декоративный характер. Убираю.

2020-09-22 08:47 UTC, ego-o commented on index.html
> +        <li><a href="#">Кредит</a></li>
Думаю, что здесь нет необходимости ни в поп-апе, ни в фолбэке. Эти элементы являются переключателями вкладкок, сами вкладки находятся на той же странице. 

Если же JavaScript на странице не загрузился, или по каким либо причинам не работет, то можно эти вкладки отобразить друг под другом, чтобы все 3 были видны пользователю. Если JavaScript загрузился и работает, то мы при помощи него скрываем все вкладки кроме одной, самой первой. И когда пользователь кликает по переключателю "Гарантия", то первая вкладка становится скрытой и открывается вторая.

Можно конечно их сделать и ссылками, прописать для них запасные адреса страниц, но зачем? Все эти элементы и так уже на странице, они не перекрывают основную область сайта (как поп-апы) и со страницей можно спокойно взаимодействовать.

2020-09-22 08:48 UTC, Lyukman commented on index.html
> +      <h2>Панель</h2>
Под фильтрами имел ввиду что это группировка номенклатуры магазина. С логической точки зрения для меня что каталоги, что фильтры это логические группировки по различными свойствам номенклатуры. Как их будет разбивать контент-менеджер я не знаю.

2020-09-22 08:50 UTC, ego-o commented on index.html
> +        <li><a href="#">Кредит</a></li>
Поэтому я счел, что здесь ссылки не нужны, достаточно обычных кнопок, и скинул ссылку на статью, чтобы, возможно, переосмыслить это дело. Если оставишь их ссылками это тоже нормально, я не буду это зачитывать как ошибку.

2020-09-22 08:59 UTC, Lyukman commented on index.html
> +            <button type="button">В закладки</button>
Не понял в чем замечание. Стиль рано написал? В качестве коммента. Выбрал кнопку, потому как в закладки без JS не знаю как запихнуть. Кнопку "Купить" нужно форму делать. Страницы чекаута нет. В скрытом поле передавать артикул или в H3 не могу понять.

2020-09-22 09:00 UTC, Lyukman commented on index.html
> +      <h2>Популярные ПРОИзводители:</h2>
Да, я уже понял. Спасибо.

2020-09-22 09:08 UTC, Lyukman commented on index.html
> +            <button type="button">В закладки</button>
Много форм на странице. Насколько это хорошо?

2020-09-22 09:15 UTC, ego-o commented on index.html
> +            <button type="button">В закладки</button>
Думаю, что нам проще будет это обсудить сегодня на консультации) Сейчас, к сожалению, не могу постоянно отвлекаться

2020-09-23 15:04 UTC, ego-o requested changes
Код стал намного лучше, и страницы теперь выглядят тоже хорошо! Но еще есть, что подправить, поэтому жду финальной версии) Молодец!

2020-09-23 15:04 UTC, ego-o commented on catalog.html
> +    <button type="button">Закрыть</button>
На этой странице нет кнопки "написать нам", а значит и разметка для данного попапа тут будет избыточной

2020-09-23 15:04 UTC, ego-o commented on catalog.html
> +    <button type="button">Закрыть</button>
То же самое, на этой странице нет блока с картой, который открывает попап с большой картой, значит его разметка на этой странице избыточна

2020-09-23 15:04 UTC, ego-o commented on catalog.html
> +</body>
Для данной страницы (и главной страницы сайта тоже) есть еще один поп-ап, который должен показываться, когда мы кликаем по кнопке "купить" у товара. Находится он на странице каталога в фигме

![image](https://user-images.githubusercontent.com/13464048/94030877-bd109d00-fdd7-11ea-9438-e03c5013cfae.png)

2020-09-23 20:17 UTC, Lyukman commented on index.html
> +        </li>
Нужны пояснения. В приведенном примере 2 листовых тега на одной строке. Если сложить как ты предложил, то будет 3. Или речь про вложенность? Я как раз и старался следовать правилу, чтобы если в ветке документа последние 2 элемента не больших, то объединить их в одну строку для улучшения читабельности.

2020-09-23 20:50 UTC, Lyukman commented on catalog.html
> +        <label>По функционалу<input type="radio" value="by-function" name="sortby"></label>
Как сделать пересечение параметров?

2020-09-23 20:54 UTC, Lyukman commented on catalog.html
> +        <label>По функционалу<input type="radio" value="by-function" name="sortby"></label>
<a href="catalog.html?sort_by=cost&sort_type=sort-type">По цене</a>
        <a href="catalog.html?sort_by=type&sort_type=sort-type">По типу</a>
        <a href="catalog.html?sort_by=func&sort_type=sort-type">По функционалу</a>
        <a href="catalog.html?sort_by=sort-by&sort_type=asc">По возрастанию</a>
        <a href="catalog.html?sort_by=sort-by&sort_type=desc">По убыванию</a>

2020-09-23 20:56 UTC, Lyukman commented on catalog.html
> +        <label>По функционалу<input type="radio" value="by-function" name="sortby"></label>
Нужно параметры как-то передавать sort-type, sort-by

2020-09-24 07:13 UTC, ego-o commented on index.html
> +        </li>
В главной навигации:
```
<li><a href="#">Пункт меню</a></li>
<li><a href="#">Пункт меню</a></li>
<li><a href="#">Пункт меню</a></li>
```
Это удобно читать, потому что знаешь, что одна строка - один пункт меню

В списке категорий список получается развернутым, и один пункт списка занимает уже не одну строчку, а три. Код разрастается вниз и получаются такие вот пирамиды
```
<li>
  <h3>Материалы</h3><a href="#">На любой вкус</a>
</li>
<li>
  <h3>Материалы</h3><a href="#">На любой вкус</a>
</li>
<li>
  <h3>Материалы</h3><a href="#">На любой вкус</a>
</li>
```
Поэтому, раз уж этот список все равно уже развернут, можно развернуть и оставшиеся теги. Потому что глазам удобнее скользить сверху вниз в поисках нужного тега, чем слева-направо. 
```
<li>
  <h3>Материалы</h3>
  <a href="#">На любой вкус</a>
</li>
<li>
  <h3>Материалы</h3>
  <a href="#">На любой вкус</a>
</li>
<li>
  <h3>Материалы</h3>
  <a href="#">На любой вкус</a>
</li>
```

Это опять же просто рекомендация, которая исходит из моего личного опыта. Тебе может быть удобнее по другому, я просто обратил на это внимание. Если это было сделано по какому-то принципу, как ты и сказал, два тега в одной строке допустимо - то все впорядке. Главное тогда, чтобы и в остальных местах и на других страницах это правило тоже работало и применялось

2020-09-24 07:28 UTC, ego-o commented on catalog.html
> +        <label>По функционалу<input type="radio" value="by-function" name="sortby"></label>
О пересечении параметров пока не беспокойся. Совместить их это уже работа сервера. Как раз вчера понял, что эта тема недораскрыта и я постарался ее немного дописать себе в черновик. 

Каждая ссылка должна отвечать только за свой параметр и предавать только его. Либо она отвечает за то, по какому свойству мы сортируем (по цене, по рейтингу, ...), либо она отвечает за порядок этой сортировки (по возрастанию или по убыванию). 

---

Получается, что у нас должны быть две группы ссылок - первая группа отзвечает за параметр, по которому нужно сортировать, а вторая группа отвечает за порядок сортировки. Но если мы нажмем на ссылку **сортировать по цене**, серверу передастся параметр `sort_by=price`, а затем нажмем на ссылку **порядок сортировки по возрастанию**, и серверу передастся другая пара `order_by=asc`, а первая удалится. По какому же параметру тогда будет сортировать сервер наши отели (по цене, по количеству комнат, ...), если передастся только порядок сортировки? 

В этом случае сервер заметит, что в прошлый раз мы передавали параметр сортировки по цене и что в этот раз он не передан, но зато указан порядок сортировки. Сервер умный, и он возьмет последний переданный ему параметр сортировки (по цене), и отсортирует его в том порядке, который мы указали перейдя по последней ссылке. 

В случае же, если мы ещё явно не указывали серверу, по какому параметру хотим сортировать (по цене, по количеству комнат, ...), например, когда мы только в первый раз попали на страницу, то он возьмет параметр, который был указан программистом по умолчанию, и остортирует по нему.

-----

На этом курсе мы учимся писать разметку, а не как взаимодействовать с сервером, поэтому, можно в ссылках можно не передавать никакие значения вообще. Главное, чтобы эти элементы были размечены ссылками. А там уже программист, который будет "натягивать" разметку на реальный сайт уже сам подставит нужные параметры в эти ссылки

2020-09-25 07:10 UTC, ego-o approved these changes
Практически все выполнено! Из-за пары недочетов я сейчас не буду отклонять ДЗ, чтобы уже можно было приступать к следующим. Ну и будь готов к тому, что разметка в будущих заданиях все равно будет меняться, потому что когда приступаешь к стилизации понимаешь, что некоторые элементы было бы удобнее разместить по другому, некоторые переписать вот так, и т.д. Поэтому, без правок в разметке все равно не обойтись

Из недочетов:
- Забыта кнопка выхода пользователя из профиля на странице каталога
- Имена файлов не должны содержать кириллицу (русские буквы) (интерскол.png)
- На главную страницу тоже надо будет добавить всплывающее окно "товар добавлен в корзину", так как там тоже выводится список товаров, и их тоже можно добавить в корзину прямо оттуда

Советую записать себе их куда-то, чтобы не забыть поправить потом

Задания принимаю, хорошая работа!

2020-09-25 07:10 UTC, merged